/* Generated by Frama-C */
#include "stddef.h"
#include "stdio.h"
/*@ requires valid_read_string(format); */
int printf_va_2(char const * restrict format, int param0);

void FazAlgov2_slice_1(int n)
{
  int i;
  int j;
  int controle = 0;
  i = 1;
  while (i < n - 1) {
    j = i + 1;
    while (j <= n) {
      controle ++;
      j ++;
    }
    i ++;
  }
  controle = (controle * n) / 2;
  printf_va_2("%d",controle);
  return;
}

/*@ requires \valid(param0);
    requires valid_read_string(format);
    ensures \initialized(param0);
 */
int fscanf_va_1(FILE * restrict stream, char const * restrict format,
                int *param0);

/*@ requires valid_read_string(format); */
int printf_va_5(char const * restrict format, int param0);

int main(char **argv)
{
  int __retres;
  FILE *fp;
  int num;
  int count = 0;
  fp = fopen((char const *)*(argv + 1),"r");
  while (1) {
    int tmp;
    tmp = fscanf_va_1(fp,"%d",& num);
    if (! (tmp == 1)) break;
    count ++;
  }
  int n = count;
  printf_va_5("QUANTIDADE DE ITEMS: %d",n);
  FazAlgov2_slice_1(n);
  __retres = 0;
  return __retres;
}


/* Generated by Frama-C */
#include "errno.h"
#include "stdarg.h"
#include "stddef.h"
#include "stdio.h"
/*@ requires valid_read_string(format); */
int printf_va_2(char const * restrict format, int param0);

void FazAlgov2_slice_1(int n)
{
  int i;
  int j;
  int controle = 0;
  i = 1;
  while (i < n - 1) {
    j = i + 1;
    while (j <= n) {
      controle ++;
      j ++;
    }
    i ++;
  }
  controle = (controle * n) / 2;
  printf_va_2("%d",controle);
  return;
}

/*@ requires \valid(param0);
    requires valid_read_string(format);
    ensures \initialized(\old(param0));
 */
int fscanf_va_1(FILE * restrict stream, char const * restrict format,
                int *param0);

/*@ requires valid_read_string(format); */
int printf_va_5(char const * restrict format, int param0);

int main(char **argv)
{
  int __retres;
  FILE *fp;
  int num;
  int count = 0;
  fp = fopen((char const *)*(argv + 1),"r");
  while (1) {
    {
      int tmp;
      tmp = fscanf_va_1(fp,"%d",& num);
      if (! (tmp == 1)) break;
      count ++;
    }
  }
  int n = count;
  printf_va_5("QUANTIDADE DE ITEMS: %d",n);
  FazAlgov2_slice_1(n);
  __retres = 0;
  return __retres;
}


